name: Moritz Jung
markdown: kramdown
permalink: /blog/:year/:month/:day/:title#
collections: 
  blender-projects:
    output: true
    permalink: /:collection/:title
  programming-projects:
    output: true