name: Moritz Jung
markdown: kramdown
port: 4000
collections: 
  art-projects:
    output: true
    permalink: /:collection/:title
  programming-projects:
    output: true
    permalink: /:collection/:title